package main

func main() {
	//hello_world()
	//variables()
	//complexian()
	//point()
	//consta()
	//arary()
	//slices()
	//mape()
	//structe()
	// call_funcs()
	//normal_closer_func()
	//metho()
	//func_with_error()
	//pan()
	//various_for()
	//control_flow()
	//interfaces()
	//start()
	//inputTake()
	//formatting_output()
	//timer()
	//calculate_time()
	//elapsed_time()
	//other_way()
	//bedtime()
	//calc_time()
	//formatting_data_types()
	//see_defer()
	//taking_user_input()
	//local_or_utc()
	//func_pass()
	//any_store_var()
	panic_recover()

}
